# Generated by Django 5.2.4 on 2025-07-13 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy_holder', '0003_alter_policy_options_alter_policyholder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('claim_type', models.CharField(choices=[('Health', 'Health'), ('Property', 'Property'), ('Vehicle', 'Vehicle'), ('Business', 'Business')], max_length=20)),
                ('tags', models.CharField(choices=[('None', 'None'), ('Fraud Preview', 'Fraud Preview'), ('Escalated', 'Escalated'), ('URGENT', 'URGENT')], max_length=20)),
                ('incident_time', models.TimeField()),
                ('incident_date', models.DateField()),
                ('location_of_incident', models.TextField()),
                ('description', models.TextField()),
                ('document', models.ImageField(upload_to='')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_holder.policy')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_holder.policyholder')),
            ],
        ),
    ]
