# Generated by Django 5.2.4 on 2025-07-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='document',
            field=models.ImageField(help_text='upload document and images', upload_to=''),
        ),
    ]
