# Generated by Django 5.2.4 on 2025-07-14 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_alter_claim_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='document',
            field=models.ImageField(help_text='upload document and images', upload_to='claims/'),
        ),
    ]
