# Generated by Django 5.2.4 on 2025-07-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_alter_claim_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='document',
            field=models.FileField(help_text='upload document and images', null=True, upload_to='claims/'),
        ),
    ]
