# Generated by Django 5.2.4 on 2025-07-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_alter_claim_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='images',
            field=models.ImageField(null=True, upload_to='claims/images/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='document',
            field=models.FileField(null=True, upload_to='claims/documents/'),
        ),
    ]
