# Generated by Django 5.2.4 on 2025-07-15 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_claim_images_alter_claim_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='next_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='next_action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Active', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='urgency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('Health', 'Health'), ('Property', 'Property'), ('Vehicle', 'Vehicle'), ('Business', 'Business')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='tags',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Processing', 'Processing'), ('Waiting for customer action', 'Waiting for customer action'), ('AI decision ready', 'AI decision ready'), ('Need manual review', 'Need manual review'), ('Sent to manager', 'Sent to manager'), ('Awaiting payout', 'Awaiting payout'), ('Paid', 'Paid'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='New', max_length=225, null=True),
        ),
    ]
