# Generated by Django 5.2.4 on 2025-08-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_claim_claim_notes_claim_claim_officer_and_more'),
        ('policy_holder', '0003_alter_policy_options_alter_policyholder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policy_holder.policy'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='policy_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policy_holder.policyholder'),
        ),
    ]
