# Generated by Django 5.2.4 on 2025-08-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0008_alter_claim_policy_alter_claim_policy_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Email address of the claim submitter', max_length=255, null=True),
        ),
    ]
