# Generated by Django 5.2.4 on 2025-08-14 12:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_claim_sender_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('UPDATED', 'Claim Updated'), ('CREATED', 'Claim Created'), ('ESCALATED', 'Claim Escalated'), ('APPROVED', 'Claim Approved'), ('REJECTED', 'Claim Rejected'), ('COMMENT_ADDED', 'Comment Added'), ('FILE_ATTACHED', 'File Attached')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(default=dict, help_text='Stores additional context about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='claim.claim')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim Audit Log',
                'verbose_name_plural': 'Claim Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
