# Generated by Django 5.2.4 on 2025-08-14 15:45

import claim.models.attachment
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0010_claimauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded file', upload_to=claim.models.attachment.claim_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp', 'txt', 'rtf', 'csv', 'json', 'xml', 'zip', 'rar', '7z', 'tar', 'gz']), claim.models.attachment.validate_file_size])),
                ('original_filename', models.CharField(help_text='Original filename of the uploaded file', max_length=255)),
                ('file_type', models.CharField(help_text="File type/category (e.g., 'document', 'image', 'spreadsheet')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(help_text='The claim this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='claim.claim')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim Attachment',
                'verbose_name_plural': 'Claim Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
