# Generated by Django 5.2.4 on 2025-07-15 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Auto Insurance', 'Auto Insurance'), ('IT/Compliance', 'IT/Compliance'), ('Health Claims', 'Health Claims'), ('General Claims', 'General Claims')], default='Auto Insurance', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=255),
        ),
    ]
