# Generated by Django 5.2.4 on 2025-07-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_staff_customuser_created_at_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=225),
            preserve_default=False,
        ),
    ]
