# Generated by Django 5.2.4 on 2025-08-14 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('role_changed', 'User Role Changed'), ('claim_created', 'Claim Created'), ('claim_updated', 'Claim Updated'), ('claim_status_changed', 'Claim Status Changed'), ('claim_deleted', 'Claim Deleted'), ('claim_file_uploaded', 'Claim File Uploaded'), ('claim_file_deleted', 'Claim File Deleted'), ('settings_changed', 'System Settings Changed'), ('maintenance_mode', 'Maintenance Mode Toggled'), ('api_call', 'API Call'), ('api_error', 'API Error'), ('other', 'Other')], help_text='The type of action that was performed', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('object_id', models.UUIDField(blank=True, help_text='The ID of the related object', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the client', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status code of the response', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the action failed', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='The type of the related object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['ip_address'], name='audit_audit_ip_addr_685e3f_idx')],
            },
        ),
    ]
