# Generated by Django 5.2.4 on 2025-07-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('coverage', models.TextField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('policy_holder_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('seniority', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='policy_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_claims', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('last_renewal_date', models.DateField()),
                ('next_renewal_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Lapsed', 'Lapsed'), ('Blacklisted', 'Blacklisted')], default='Active', max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_holder.policy')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_holder.policyholder')),
            ],
        ),
    ]
