# Generated by Django 5.2.4 on 2025-07-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_holder', '0002_rename_policy_subscription_policysubscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['policy_id'], 'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='policyholder',
            options={'ordering': ['policy_holder_id'], 'verbose_name': 'PolicyHolder', 'verbose_name_plural': 'PoliciesHolders'},
        ),
        migrations.AlterModelOptions(
            name='policysubscription',
            options={'ordering': ['policy_holder'], 'verbose_name': 'PolicySubscription', 'verbose_name_plural': 'PoliciesSubscription'},
        ),
    ]
